// Ethiopian/African-focused business categories
export const businessCategories = {
  "Animals & Pets": [
    "Animal Health",
    "Animal Parks & Zoo",
    "Cats & Dogs",
    "Horses & Riding",
    "Pet Services",
    "Pet Stores",
    "Livestock & Farm Animals",
  ],
  "Beauty & Well-being": [
    "Cosmetics & Makeup",
    "Hair Care & Styling",
    "Personal Care",
    "Salons & Clinics",
    "Tattoos & Piercings",
    "Wellness & Spa",
    "Yoga & Meditation",
    "Traditional Beauty Treatments",
  ],
  "Business Services": [
    "Administration & Services",
    "Associations & Centers",
    "HR & Recruiting",
    "Import & Export",
    "IT & Communication",
    "Office Space & Supplies",
    "Print & Graphic Design",
    "Research & Development",
    "Sales & Marketing",
    "Shipping & Logistics",
    "Wholesale",
    "Business Consulting",
  ],
  "Construction & Manufacturing": [
    "Architects & Engineers",
    "Building Materials",
    "Chemicals & Plastic",
    "Construction Services",
    "Contractors & Consultants",
    "Factory Equipment",
    "Garden & Landscaping",
    "Industrial Supplies",
    "Manufacturing",
    "Production Services",
    "Tools & Equipment",
    "Traditional Construction",
  ],
  "Education & Training": [
    "Colleges & Universities",
    "Courses & Classes",
    "Education Services",
    "Language Learning",
    "Music & Theater Classes",
    "School & High School",
    "Special Schools",
    "Vocational Training",
    "Religious Education",
    "Adult Education",
  ],
  "Electronics & Technology": [
    "Appliances & Electronics",
    "Audio & Visual",
    "Computers & Phones",
    "Internet & Software",
    "Repair & Services",
    "Mobile Money Services",
    "Tech Accessories",
  ],
  "Events & Entertainment": [
    "Adult Entertainment",
    "Children's Entertainment",
    "Clubbing & Nightlife",
    "Events & Venues",
    "Gambling",
    "Gaming",
    "Museums & Exhibits",
    "Music & Movies",
    "Theater & Opera",
    "Wedding & Party",
    "Cultural Festivals",
    "Traditional Entertainment",
  ],
  "Food, Beverages & Tobacco": [
    "Agriculture & Produce",
    "African Grocery Stores",
    "Bakery & Pastry",
    "Beer & Wine",
    "Beverages & Liquor",
    "Candy & Chocolate",
    "Coffee & Tea",
    "Food Production",
    "Fruits & Vegetables",
    "Grocery Stores & Markets",
    "Lunch & Catering",
    "Meat, Seafood & Eggs",
    "Smoking & Tobacco",
    "Traditional Foods & Spices",
    "Street Food Vendors",
  ],
  "Health & Medical": [
    "Clinics",
    "Dental Services",
    "Diagnostics & Testing",
    "Doctors & Surgeons",
    "Health Equipment",
    "Hospital & Emergency",
    "Medical Specialists",
    "Mental Health",
    "Pharmacy & Medicine",
    "Physical Aids",
    "Pregnancy & Children",
    "Therapy & Senior Health",
    "Vision & Hearing",
    "Traditional Medicine",
    "Herbal Medicine",
  ],
  "Hobbies & Crafts": [
    "Art & Handicraft",
    "Astrology & Numerology",
    "Fishing & Hunting",
    "Hobbies",
    "Metal, Stone & Glass Work",
    "Music & Instruments",
    "Needlework & Knitting",
    "Outdoor Activities",
    "Painting & Paper",
    "Traditional Crafts",
    "Cultural Artifacts",
  ],
  "Home & Garden": [
    "Bathroom & Kitchen",
    "Cultural Goods",
    "Decoration & Interior",
    "Energy & Heating",
    "Fabric & Stationery",
    "Furniture Stores",
    "Garden & Pond",
    "Home & Garden Services",
    "Home Goods Stores",
    "Home Improvements",
    "Traditional Furnishings",
  ],
  "Home Services": [
    "Cleaning Service Providers",
    "Craftsman",
    "House Services",
    "House Sitting & Security",
    "Moving & Storage",
    "Plumbing & Sanitation",
    "Repair Service Providers",
    "Domestic Workers",
    "Gardeners",
  ],
  "Legal Services & Government": [
    "Customs & Toll",
    "Government Department",
    "Law Enforcement",
    "Lawyers & Attorneys",
    "Legal Service Providers",
    "Libraries & Archives",
    "Municipal Department",
    "Registration Services",
    "Community Services",
    "Traditional Courts",
  ],
  "Media & Publishing": [
    "Books & Magazines",
    "Media & Information",
    "Photography",
    "Video & Sound",
    "Local News",
    "Community Radio",
  ],
  "Money & Insurance": [
    "Accounting & Tax",
    "Banking & Money",
    "Credit & Debt Services",
    "Insurance",
    "Investments & Wealth",
    "Real Estate",
    "Microfinance",
    "Savings Groups",
    "Mobile Banking",
  ],
  "Public & Local Services": [
    "Employment & Career",
    "Funeral & Memorial",
    "Housing Associations",
    "Kids & Family",
    "Military & Veteran",
    "Nature & Environment",
    "Professional Organizations",
    "Public Services & Welfare",
    "Religious Institutions",
    "Shelters & Homes",
    "Waste Management",
    "Community Centers",
    "NGOs & Aid Organizations",
  ],
  "Restaurants & Bars": [
    "African & Ethiopian Cuisine",
    "Bars & Cafes",
    "Chinese & Korean Cuisine",
    "European Cuisine",
    "General Restaurants",
    "Japanese Cuisine",
    "Mediterranean Cuisine",
    "Middle Eastern Cuisine",
    "North & South American Cuisine",
    "Southeast Asian Cuisine",
    "Takeaway",
    "Vegetarian & Diet",
    "Traditional Restaurants",
    "Juice Houses",
    "Coffee Ceremonies",
  ],
  "Shopping & Fashion": [
    "Accessories",
    "Clothing & Underwear",
    "Clothing Rental & Repair",
    "Costume & Wedding",
    "Jewelry & Watches",
    "Malls & Marketplaces",
    "Traditional Clothing",
    "Fabric & Textiles",
    "Cultural Attire",
  ],
  Sports: [
    "Ball Games",
    "Bat-and-ball Games",
    "Bowls & Lawn Sports",
    "Dancing & Gymnastics",
    "Equipment & Associations",
    "Extreme Sports",
    "Fitness & Weight Lifting",
    "Golf & Ultimate",
    "Hockey & Ice Skating",
    "Martial arts & Wrestling",
    "Outdoor & Winter Sports",
    "Shooting & Target Sports",
    "Swimming & Water Sports",
    "Tennis & Racquet Sports",
    "Traditional Sports",
    "Football Clubs",
  ],
  "Travel & Vacation": [
    "Accommodation & Lodging",
    "Activities & Tours",
    "Airlines & Air Travel",
    "Hotels",
    "Travel Agencies",
    "Eco Tourism",
    "Cultural Tourism",
    "Safari & Wildlife",
    "Historical Sites",
  ],
  Utilities: ["Energy & Power", "Oil & Fuel", "Water Utilities", "Solar Power", "Alternative Energy"],
  "Vehicles & Transportation": [
    "Air & Water Transport",
    "Airports & Parking",
    "Auto Parts & Wheels",
    "Bicycles",
    "Cars & Trucks",
    "Motorcycle & Powersports",
    "Other Vehicles & Trailers",
    "Taxis & Public Transport",
    "Vehicle Rental",
    "Vehicle Repair & Fuel",
    "Bajaj & Tuk-tuk Services",
    "Animal Transport",
  ],
  "Agriculture & Farming": [
    "Farm Equipment",
    "Seeds & Fertilizers",
    "Irrigation Systems",
    "Livestock Farming",
    "Crop Farming",
    "Agricultural Consulting",
    "Organic Farming",
    "Beekeeping",
    "Coffee Farming",
  ],
  "Cultural & Religious": [
    "Churches & Mosques",
    "Religious Supplies",
    "Cultural Centers",
    "Traditional Ceremonies",
    "Religious Education",
    "Spiritual Services",
    "Cultural Preservation",
  ],
}

// Flatten categories for search and selection
export const flattenedCategories = Object.entries(businessCategories).reduce((acc, [category, subcategories]) => {
  acc.push(category)
  subcategories.forEach((subcategory) => {
    acc.push(`${category} > ${subcategory}`)
  })
  return acc
}, [] as string[])

// Get main categories
export const mainCategories = Object.keys(businessCategories)

// Get subcategories for a main category
export const getSubcategories = (mainCategory: string) => {
  return businessCategories[mainCategory as keyof typeof businessCategories] || []
}
